# Generated by Django 3.1.1 on 2020-09-07 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('story_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', null=True, upload_to='story_image/')),
                ('fav', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 7, 15, 9, 26, 227275))),
            ],
        ),
    ]
