# Generated by Django 3.1.1 on 2020-09-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200907_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='fav',
            new_name='favorite',
        ),
    ]
